#!/bin/bash

# $@ => "$1" $2 ...
function error() { cat <<<"$@" 1>&2; }

function help() {
	echo "Usage $(basename $0) DIR
				write DIR directory to backup"

}

function do_or_die() {
	# $1 - command, $2 - error messange
	eval $1

	#if [[ $? != 0 ]]

	if [ $? -ne 0 ]; then
		error $2
		exit $?
	fi
}


#if [ -z "$1" ]; then
if [ ! "$1" ]; then
	error "no directory"
	help
	exit 1
fi

# $1 = /etc/profile.d

TARGET=/tmp/backup/$USER
#BNAME=`basename $1`
BNAME=$(basename $1)
DNAME=$(dirname $1)
FILE=$TARGET/$BNAME.tgz

#if [ ! -d $TARGET ]; then
#	mkdir $TARGET
#tar cf $FILE $1
#gzip -f -9 $FILE

[ -d $TARGET ] || do_or_die "mkdir -p $TARGET" "mkdir $TARGET failed"

do_or_die "tar czf $FILE $1" "tar failed"
#gzip -f -9 $FILE