#!/bin/bash

# $@ => "$1" $2 ...
function error() { cat <<<"$@" 1>&2; }

function help() {
	echo "Usage $(basename $0) DIR
				write DIR directory to backup"

}

#if [ -z "$1" ]; then
if [ ! "$1" ]; then
	error "no directory"
	help
	exit 1
fi

# $1 = /etc/profile.d

TARGET=/tmp/backup
#BNAME=`basename $1`
BNAME=$(basename $1)
FILE=$TARGET/$BNAME.tar

#if [  ! -d $TARGET ]; then
#	mkdir $TARGET
#tar cf $FILE $1
#gzip -f -9 $FILE

[ -d $TARGET ] || mkdir $TARGET
tar cf $FILE $1
gzip -f -9 $FILE